services:
  - type: web
    name: InsureGuide
    runtime: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && python app.py
    envVars:
      - key: GEMINI_API_KEY
        sync: false